FROM nginx:alpine

# Создание директории для SSL сертификатов
RUN mkdir -p /etc/nginx/ssl

COPY ./certs/localhost.crt /etc/nginx/ssl
COPY ./certs/localhost.key /etc/nginx/ssl

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 443